### ISSUE TITLE
create semvar tag and update the import "codahale/hdrhistogram" to "hdrhistogram"?

### ISSUE THREAD

**Issue by spacewander** [zoidbergwill/hdrhistogram#7]
A semvar tag is helpful for dependency management tool like `go module`.
And because the test files import `codahale/hdrhistogram` instead of `hdrhistogram`, `go module` will consider `codahale/hdrhistogram` as a dependency of this project. Actually, use the `hdrhistogram` without namespace is enough.

**Comment by zoidyzoidzoid** [comment]
Hey @spacewander

Thanks for the issue.

That sounds like a great idea. I will update it.

I've been meaning to try update this repo a bunch, but feel free to file issues or make PRs if you have the time.
